# roles/webserver/handlers/main.yml

- name: Restart Apache (Debian/Ubuntu con systemd)
  ansible.builtin.service:
    name: apache2
    state: restarted
  listen: "restart webserver"
  when:
    - webserver_type == 'apache'
    - ansible_os_family == 'Debian'
    - ansible_virtualization_type != "docker"

- name: Restart Apache (Rocky/RedHat con systemd)
  ansible.builtin.service:
    name: httpd
    state: restarted
  listen: "restart webserver"
  when:
    - webserver_type == 'apache'
    - ansible_os_family == 'RedHat'
    - ansible_virtualization_type != "docker"

- name: Restart Apache (manual para Docker/Rocky)
  ansible.builtin.shell: |
    pkill -f httpd || true
    nohup /usr/sbin/httpd -D FOREGROUND &
  listen: "restart webserver"
  when:
    - webserver_type == 'apache'
    - ansible_os_family == 'RedHat'
    - ansible_virtualization_type == "docker"
  changed_when: true
  failed_when: false

# PHP-FPM
- name: Restart PHP-FPM (Debian/Ubuntu con systemd)
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
  listen: "restart php-fpm"
  when:
    - php_enable_php_fpm
    - ansible_os_family == 'Debian'
    - ansible_virtualization_type != "docker"

- name: Restart PHP-FPM (RedHat con systemd)
  ansible.builtin.service:
    name: php-fpm
    state: restarted
  listen: "restart php-fpm"
  when:
    - php_enable_php_fpm
    - ansible_os_family == 'RedHat'
    - ansible_virtualization_type != "docker"
