# molecule/default/verify.yml
---
- name: Verify webserver role
  hosts: all
  gather_facts: true
  tasks:
    - name: Chequear si Apache está corriendo (Debian/Ubuntu)
      ansible.builtin.command: pgrep apache2
      register: apache_status
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Chequear si Apache está corriendo (RedHat)
      ansible.builtin.command: pgrep httpd
      register: apache_status
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Verificar si Apache está corriendo (Debian)
      ansible.builtin.command: pgrep apache2
      register: apache_status
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Verificar si PHP-FPM está corriendo (solo Debian/Ubuntu)
      ansible.builtin.command: pgrep php-fpm
      register: php_fpm_status
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Verificar estado de PHP-FPM en Debian
      ansible.builtin.debug:
        msg: "PHP-FPM está corriendo en Debian"
      when: ansible_os_family == "Debian" and php_fpm_status is defined and php_fpm_status.rc == 0

    - name: Check if WordPress directory exists
      ansible.builtin.stat:
        path: "{{ wordpress_install_dir }}"
      register: wordpress_dir_stat
      failed_when: not wordpress_dir_stat.stat.exists

    - name: Check for wp-config.php and its contents
      ansible.builtin.command: cat {{ wordpress_install_dir }}/wp-config.php
      register: wp_config_content
      changed_when: false
