name: Test CI 

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test role with Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker ansible-core==2.18.4 molecule molecule-plugins[docker] 

      - name: Run Molecule steps
        run: |
          molecule destroy
          molecule syntax
          molecule create
          molecule prepare
          molecule converge
          molecule verify
          molecule destroy
